// Supabase Configuration
// This file is automatically generated when connecting to Supabase project
// Project ID: hcgbxhycfbcinbstqtzx

class SupabaseConfig {
  static const String supabaseUrl = 'https://hcgbxhycfbcinbstqtzx.supabase.co';
  static const String supabaseAnonKey = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhjZ2J4aHljZmJjaW5ic3RxdHp4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjYwMzk3NDIsImV4cCI6MjA4MTYxNTc0Mn0.VIBZ1-TMRaXaG4gbWiyB1wsBIQLWbv0tueGakUWLshw';
}
